# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20161026_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
